version: '3.3'
  # Use root/example as user/password credentials
  #version: '3.1'

services:

  db:
    #build: ./db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 111
      MARIADB_USER: artem
      MARIADB_PASSWORD: 123
#    volumes:
#       - ./database:/var/lib/mysql

  adminer:
    #build: ./adminer
    image: adminer
    restart: always
    ports:
      - 5080:8080
